package com.shineyue.cn.model;

import java.util.ArrayList;
import java.util.List;

public class TStudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_student
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public TStudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_student
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGIdIsNull() {
            addCriterion("g_id is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("g_id is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(String value) {
            addCriterion("g_id =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(String value) {
            addCriterion("g_id <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(String value) {
            addCriterion("g_id >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(String value) {
            addCriterion("g_id >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(String value) {
            addCriterion("g_id <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(String value) {
            addCriterion("g_id <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLike(String value) {
            addCriterion("g_id like", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotLike(String value) {
            addCriterion("g_id not like", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<String> values) {
            addCriterion("g_id in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<String> values) {
            addCriterion("g_id not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(String value1, String value2) {
            addCriterion("g_id between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(String value1, String value2) {
            addCriterion("g_id not between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGNameIsNull() {
            addCriterion("g_name is null");
            return (Criteria) this;
        }

        public Criteria andGNameIsNotNull() {
            addCriterion("g_name is not null");
            return (Criteria) this;
        }

        public Criteria andGNameEqualTo(String value) {
            addCriterion("g_name =", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotEqualTo(String value) {
            addCriterion("g_name <>", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThan(String value) {
            addCriterion("g_name >", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThanOrEqualTo(String value) {
            addCriterion("g_name >=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThan(String value) {
            addCriterion("g_name <", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThanOrEqualTo(String value) {
            addCriterion("g_name <=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLike(String value) {
            addCriterion("g_name like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotLike(String value) {
            addCriterion("g_name not like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameIn(List<String> values) {
            addCriterion("g_name in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotIn(List<String> values) {
            addCriterion("g_name not in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameBetween(String value1, String value2) {
            addCriterion("g_name between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotBetween(String value1, String value2) {
            addCriterion("g_name not between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGAgeIsNull() {
            addCriterion("g_age is null");
            return (Criteria) this;
        }

        public Criteria andGAgeIsNotNull() {
            addCriterion("g_age is not null");
            return (Criteria) this;
        }

        public Criteria andGAgeEqualTo(Short value) {
            addCriterion("g_age =", value, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeNotEqualTo(Short value) {
            addCriterion("g_age <>", value, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeGreaterThan(Short value) {
            addCriterion("g_age >", value, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeGreaterThanOrEqualTo(Short value) {
            addCriterion("g_age >=", value, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeLessThan(Short value) {
            addCriterion("g_age <", value, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeLessThanOrEqualTo(Short value) {
            addCriterion("g_age <=", value, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeIn(List<Short> values) {
            addCriterion("g_age in", values, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeNotIn(List<Short> values) {
            addCriterion("g_age not in", values, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeBetween(Short value1, Short value2) {
            addCriterion("g_age between", value1, value2, "gAge");
            return (Criteria) this;
        }

        public Criteria andGAgeNotBetween(Short value1, Short value2) {
            addCriterion("g_age not between", value1, value2, "gAge");
            return (Criteria) this;
        }

        public Criteria andGSexIsNull() {
            addCriterion("g_sex is null");
            return (Criteria) this;
        }

        public Criteria andGSexIsNotNull() {
            addCriterion("g_sex is not null");
            return (Criteria) this;
        }

        public Criteria andGSexEqualTo(String value) {
            addCriterion("g_sex =", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexNotEqualTo(String value) {
            addCriterion("g_sex <>", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexGreaterThan(String value) {
            addCriterion("g_sex >", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexGreaterThanOrEqualTo(String value) {
            addCriterion("g_sex >=", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexLessThan(String value) {
            addCriterion("g_sex <", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexLessThanOrEqualTo(String value) {
            addCriterion("g_sex <=", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexLike(String value) {
            addCriterion("g_sex like", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexNotLike(String value) {
            addCriterion("g_sex not like", value, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexIn(List<String> values) {
            addCriterion("g_sex in", values, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexNotIn(List<String> values) {
            addCriterion("g_sex not in", values, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexBetween(String value1, String value2) {
            addCriterion("g_sex between", value1, value2, "gSex");
            return (Criteria) this;
        }

        public Criteria andGSexNotBetween(String value1, String value2) {
            addCriterion("g_sex not between", value1, value2, "gSex");
            return (Criteria) this;
        }

        public Criteria andGTeamIdIsNull() {
            addCriterion("g_team_id is null");
            return (Criteria) this;
        }

        public Criteria andGTeamIdIsNotNull() {
            addCriterion("g_team_id is not null");
            return (Criteria) this;
        }

        public Criteria andGTeamIdEqualTo(String value) {
            addCriterion("g_team_id =", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdNotEqualTo(String value) {
            addCriterion("g_team_id <>", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdGreaterThan(String value) {
            addCriterion("g_team_id >", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("g_team_id >=", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdLessThan(String value) {
            addCriterion("g_team_id <", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdLessThanOrEqualTo(String value) {
            addCriterion("g_team_id <=", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdLike(String value) {
            addCriterion("g_team_id like", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdNotLike(String value) {
            addCriterion("g_team_id not like", value, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdIn(List<String> values) {
            addCriterion("g_team_id in", values, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdNotIn(List<String> values) {
            addCriterion("g_team_id not in", values, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdBetween(String value1, String value2) {
            addCriterion("g_team_id between", value1, value2, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGTeamIdNotBetween(String value1, String value2) {
            addCriterion("g_team_id not between", value1, value2, "gTeamId");
            return (Criteria) this;
        }

        public Criteria andGStatusIsNull() {
            addCriterion("g_status is null");
            return (Criteria) this;
        }

        public Criteria andGStatusIsNotNull() {
            addCriterion("g_status is not null");
            return (Criteria) this;
        }

        public Criteria andGStatusEqualTo(Short value) {
            addCriterion("g_status =", value, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusNotEqualTo(Short value) {
            addCriterion("g_status <>", value, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusGreaterThan(Short value) {
            addCriterion("g_status >", value, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("g_status >=", value, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusLessThan(Short value) {
            addCriterion("g_status <", value, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusLessThanOrEqualTo(Short value) {
            addCriterion("g_status <=", value, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusIn(List<Short> values) {
            addCriterion("g_status in", values, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusNotIn(List<Short> values) {
            addCriterion("g_status not in", values, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusBetween(Short value1, Short value2) {
            addCriterion("g_status between", value1, value2, "gStatus");
            return (Criteria) this;
        }

        public Criteria andGStatusNotBetween(Short value1, Short value2) {
            addCriterion("g_status not between", value1, value2, "gStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_student
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_student
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}