package com.shineyue.cn.model;

public class TStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.g_id
     *
     * @mbggenerated
     */
    private String gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.g_name
     *
     * @mbggenerated
     */
    private String gName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.g_age
     *
     * @mbggenerated
     */
    private Short gAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.g_sex
     *
     * @mbggenerated
     */
    private String gSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.g_team_id
     *
     * @mbggenerated
     */
    private String gTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.g_status
     *
     * @mbggenerated
     */
    private Short gStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.g_id
     *
     * @return the value of t_student.g_id
     *
     * @mbggenerated
     */
    public String getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.g_id
     *
     * @param gId the value for t_student.g_id
     *
     * @mbggenerated
     */
    public void setgId(String gId) {
        this.gId = gId == null ? null : gId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.g_name
     *
     * @return the value of t_student.g_name
     *
     * @mbggenerated
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.g_name
     *
     * @param gName the value for t_student.g_name
     *
     * @mbggenerated
     */
    public void setgName(String gName) {
        this.gName = gName == null ? null : gName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.g_age
     *
     * @return the value of t_student.g_age
     *
     * @mbggenerated
     */
    public Short getgAge() {
        return gAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.g_age
     *
     * @param gAge the value for t_student.g_age
     *
     * @mbggenerated
     */
    public void setgAge(Short gAge) {
        this.gAge = gAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.g_sex
     *
     * @return the value of t_student.g_sex
     *
     * @mbggenerated
     */
    public String getgSex() {
        return gSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.g_sex
     *
     * @param gSex the value for t_student.g_sex
     *
     * @mbggenerated
     */
    public void setgSex(String gSex) {
        this.gSex = gSex == null ? null : gSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.g_team_id
     *
     * @return the value of t_student.g_team_id
     *
     * @mbggenerated
     */
    public String getgTeamId() {
        return gTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.g_team_id
     *
     * @param gTeamId the value for t_student.g_team_id
     *
     * @mbggenerated
     */
    public void setgTeamId(String gTeamId) {
        this.gTeamId = gTeamId == null ? null : gTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.g_status
     *
     * @return the value of t_student.g_status
     *
     * @mbggenerated
     */
    public Short getgStatus() {
        return gStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.g_status
     *
     * @param gStatus the value for t_student.g_status
     *
     * @mbggenerated
     */
    public void setgStatus(Short gStatus) {
        this.gStatus = gStatus;
    }
}