server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/shineyue/demo/pojo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shineyue?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: JH123456
    driver-class-name: org.postgresql.Driver