package com.shineyue.cn.mapper;

import com.shineyue.cn.model.TStudent;
import com.shineyue.cn.model.TStudentExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

@Mapper
public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    int countByExample(TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    int deleteByExample(TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_student",
        "where g_id = #{gId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_student (g_id, g_name, ",
        "g_age, g_sex, g_team_id, ",
        "g_status)",
        "values (#{gId,jdbcType=VARCHAR}, #{gName,jdbcType=VARCHAR}, ",
        "#{gAge,jdbcType=SMALLINT}, #{gSex,jdbcType=VARCHAR}, #{gTeamId,jdbcType=VARCHAR}, ",
        "#{gStatus,jdbcType=SMALLINT})"
    })
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    int insertSelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    List<TStudent> selectByExample(TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "g_id, g_name, g_age, g_sex, g_team_id, g_status",
        "from t_student",
        "where g_id = #{gId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    TStudent selectByPrimaryKey(String gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TStudent record, @Param("example") TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TStudent record, @Param("example") TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated
     */
    @Update({
        "update t_student",
        "set g_name = #{gName,jdbcType=VARCHAR},",
          "g_age = #{gAge,jdbcType=SMALLINT},",
          "g_sex = #{gSex,jdbcType=VARCHAR},",
          "g_team_id = #{gTeamId,jdbcType=VARCHAR},",
          "g_status = #{gStatus,jdbcType=SMALLINT}",
        "where g_id = #{gId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TStudent record);
}