package com.shineyue.cn.mapper;

import com.shineyue.cn.model.TTeam;
import com.shineyue.cn.model.TTeamExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

import javax.annotation.ManagedBean;

@Mapper
public interface TTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    int countByExample(TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    int deleteByExample(TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_team",
        "where g_id = #{gId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_team (g_id, g_name)",
        "values (#{gId,jdbcType=VARCHAR}, #{gName,jdbcType=VARCHAR})"
    })
    int insert(TTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    int insertSelective(TTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    List<TTeam> selectByExample(TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "g_id, g_name",
        "from t_team",
        "where g_id = #{gId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    TTeam selectByPrimaryKey(String gId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TTeam record, @Param("example") TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TTeam record, @Param("example") TTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated
     */
    @Update({
        "update t_team",
        "set g_name = #{gName,jdbcType=VARCHAR}",
        "where g_id = #{gId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TTeam record);
}